### PR TITLE
Stay-In-Touch: Milestone 1

### PR DESCRIPTION
**Pull request by kwizl**
# Entity Relationship Diagram (ERD)

- This diagram represents the entities or tables that build up our application at the database level. It shows how they interact with each other and the type of data that they store. With this, the developer show get a clear picture of how the application will be built from the ground up. It also makes writing the code for the application easier.

### CODE REVIEW

**Review by majovanilla — CHANGES_REQUESTED** [review]
Hi team!

## Nice try on the first milestone! 👍

However, I'm unable to see your file. It seems that it was uploaded in an incorrect way. I suggest you add it as an image in the img folder, just in case it's the format.

Also, your readme is quite generic now. You need to add the information necessary for people to use your project and run it. You have a very good idea of what's going to look like, so you can start from there and then update it when you are finished.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Comment by abdelp** [comment]
- png image uploaded inside /app/assets/images
it was a little confusing that it was specified to put it inside the "doc" folder and not specified the format of the document.
- /doc folder removed
- README.md file updated

**Comment by abdelp** [comment]
we decided to divide the confirmed friendships from the invitations because we consider that way will be faster the search of the friends, let's supposed that there are a million invitations, which 999,999 of them are unconfirmed, to search for the friends of a user, we are going to need search through the 999,999 unconfirmed invitations, instead of just having the confirmed ones in another table

**Comment by abdelp** [comment]
we decided to divide the confirmed friendships from the invitations because we consider that way will be faster the search of the friends, let's suppose that there are a million invitations, which 999,999 of them are unconfirmed, to search for the friends of a user, we are going to need to search through the 999,999 unconfirmed invitations, instead of just having the confirmed ones in another table. Also, we decided to have "duplicated" friendship rows. E.g.: user 1 is a friend of user 2, as user 2 is a friend of user 1 because it reduces the complexity of the queries and the checks to insert it as explained here: https://explainextended.com/2009/03/07/selecting-friends/

**Review by wathigo — CHANGES_REQUESTED** [review]
### Changes Required
Great work guys :clap: 
Let's fix some issues before we move on.

**REQUIRED**
* We don't need timeline relation. Timeline is just the view where we will be displaying user's posts and friend's posts.
* You are right about creating and two rows for mutual friendship friendship but friendship table is enough. We only add an additional row with reversed user-friend pair upon friendship confirmation.


**After implementing the changes, submit another request for review.**

_Feel free to reach out via slack in case of any issue/clarification._

**Good luck :four_leaf_clover: 
Simon Wathigo**

**Comment by abdelp** [comment]
Right, I was confusing it with an object-oriented DB

**Review by maelfosso — APPROVED** [review]
# Congratulations :clap: 

You can merge it :+1: 
Good continuation :handshake: 

Mael FOSSO

**Pull request merged**
