### PR TITLE
Social Media Application: Stay In Touch

### PR DESCRIPTION
**Pull request by kwizl**
# Milestone 5
This is a social media application that enables users to sign up, log in, create posts, comment on posts and like posts. It has been developed using the MVP (Minimum Viable Product) approach. Below are its functionalities.

**As a guest user:**
- Create an account and login.
- Ability to Sign Out

**As a logged-in user:**
- See all users list.
- See selected user page with their user name and all posts written by them (the most recent posts on the top).
- Ability to send a friendship invitation.
- Able to Invite user who is not my friend.
- See pending friendship invitations sent to me from other users.
- Able to accept or reject friendships invitation.
- Able to create new posts (text only).
- Able to like/dislike posts (but I can like single post only once).
- Able to add comments to posts.
- Able to see “Timeline” page with posts (with number of likes and comments) written by me and all my friends (the most recent posts on the top).

### CODE REVIEW

**Comment by uryelah** [comment]
Hi **Abdel Pérez Téllez & Martin Njoroge**, I'm Sarah your reviewer for this PR 👩‍🚀 

Great job with your project so far, great use of helpers with the `send_button` method and good job with the complex sql queries.

You still need to work on some issues before you're good to go, but I'm sure you got this! 💪 

## Changes Required 🏗️ 🐛 💡

- [x] There should be a button to invite user to friendship on both the users index view and on the user show view.

- [x] Update your tests so they reflect the current requirements for the friendships and user models.

- [x] Model logic, ex: `find_by_sql`, should be in the models not controllers. You can make methods at the model to refactor it out of the controllers.

- [x] View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb).
 There should be absolutely NO logic in views. (<% if ..., <% events.each ..., etc)
Some useful StackOverflow threads on helpers:
https://stackoverflow.com/questions/2194745/rails-refactoring-views-helpers-how-does-it-all-go-together
https://stackoverflow.com/questions/27995582/how-to-properly-refactor-a-simple-if-else-logic-in-views-for-ror


-----

 **Kindly fix the pointed out issues before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by kwizl** [comment]
Hi Sarah. We have implemented all the changes. The only issue is with the last change. We removed the logic from the views that we created. The views that were created by the Microverse team and the ones generated by devise we haven't touched.

**Comment by uryelah** [comment]
@kwizl I'm consulting with the TSE team about the issue you raised but initially the review rubric indicates there should be no logic in the views whatsoever. I can't give you a definitive answer on how that relates with the forked files though. Sorry about that, but I think you can already go ahead and ask for a new review.

**Review by nikasulo — APPROVED** [review]
# Great job! @kwizl and @abdelp :medal_military: 
Please merge and keep moving forward, I wish you the very best and see you at the top :rocket:

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
